local everything = {
    "status",
    "   ",
    "🟢 : Menu",
    "    ",
    "Tab 1 - Hop Sever",
    "🟢 : Hop Sever",
    "🟢 : Hop Sever Low Player",
    "🟠 : Best Ping - [ Beta ]",
    "🟢 : Rejoin Current Server",
    "     ",
    "Tab 2 - Free Sever Vip",
    "🟢 : Free Sever Vip V1",
    "🟢 : Free Sever Vip v2",
    "    ",
    "Tab 3 - ... Player [ Beta ]",
    "🟠 : Hop Server ( Under 2 Players )  - [ Beta ]",
    "🟠 : Hop Server ( Under 4 Players )  - [ Beta ]",
    "🟠 : Hop Server ( Under 6 Players )  - [ Beta ]",
    "🟠 : Hop Server ( Under 8 Players )  - [ Beta ]",
    "🟠 : Hop Server ( Under 10 Players ) - [ Beta ]",
    "🟠 : Hop Server ( Under 12 Players ) - [ Beta ]",
    "    ",
    "Tab 4 - Other Features",
    "🟢 : Leave If Admin Blox Fruits Join V1",
    "🟢 : Leave If Admin Blox Fruits Join V2",
    "    ",
    "Tab 5 - Keyboard",
    "🟢 F9 Key",
    "   ",
    "   ",
    "   ",
    "   ",
    "   ",
    "Status Announcement",
    "🟢 : WORKING",
    "🟠 : Experimental Features, Working Good",
    "⚪ : Troubleshooting Underway, Only Some Features Are Working",
    "🔴 : Dead, Never Works Again, or Comes Back After a Long Time",

}

for i, v in next, everything do
    print(tostring(v))
    task.wait()
end
